Devin Liu
A20483790
CS512

In [191]:
import numpy as np

### PART A

In [192]:
# reshape to make it a 3, 1 matrix instead of 1, 3

P = np.array([2, -1, 4]).reshape(3,1)
Q = np.array([0, 3, 5]).reshape(3,1)
R = np.array([1, -2, 2]).reshape(3,1)

In [193]:
# 1
result_1 = 3 * P + 2 * Q
print("3P + 2Q:\n", result_1)

3P + 2Q:
 [[ 6]
 [ 3]
 [22]]


In [194]:
# 2
p_mag = np.linalg.norm(P)
p_unit_vec = P / p_mag
result_2 = p_unit_vec
print("Unit vector in the direction of P:\n", result_2)

Unit vector in the direction of P:
 [[ 0.43643578]
 [-0.21821789]
 [ 0.87287156]]


In [195]:
# 3
p_relative_to_y = np.arccos(p_unit_vec[1])
print("Magnitude of P: ", p_mag)
result_3 = p_relative_to_y
print("Angle of P relative to positive Y axis: ", result_3)

Magnitude of P:  4.58257569495584
Angle of P relative to positive Y axis:  [1.7907843]


In [196]:
# 4
result_4 = p_unit_vec
print("Direction cosine of P: \n", result_4)

Direction cosine of P: 
 [[ 0.43643578]
 [-0.21821789]
 [ 0.87287156]]


In [197]:
# 5
p_q_dot = P.T.dot(Q)
q_mag = np.linalg.norm(Q)
result_5 = p_q_dot / (p_mag * q_mag)
print("Angle between P and Q: ", result_5)

Angle between P and Q:  [[0.63620901]]


In [198]:
# 6
result_6 = f'P dot Q: {p_q_dot}\nQ dot P: {Q.T.dot(P)}'
print(result_6)

P dot Q: [[17]]
Q dot P: [[17]]


In [199]:
# 7
angle_between_pq = np.arccos(result_5)
dot_product_using_angle = p_mag * q_mag * np.cos(angle_between_pq)
result_7 = dot_product_using_angle
print("dot product using angle: ", result_7)

dot product using angle:  [[17.]]


In [200]:
# 8
q_proj_p = p_q_dot/p_mag
result_8 = q_proj_p
print("Scalar projection of Q onto P: ", result_8)

Scalar projection of Q onto P:  [[3.70970413]]


In [201]:

# 9
vector_perp_to_p = np.array([-1, 2, 1]).reshape(3, 1)
result_9 = vector_perp_to_p
print("Vector perpendicular to P: \n", vector_perp_to_p, "\n")
print(P.T.dot(vector_perp_to_p))

Vector perpendicular to P: 
 [[-1]
 [ 2]
 [ 1]] 

[[0]]


In [202]:
# 10
p_cross_q = np.cross(P.T, Q.T).reshape(3, 1)
q_cros_p = np.cross(Q.T, P.T).reshape(3, 1)
print("P cross Q:\n", p_cross_q)
print("Q cross P:\n", q_cros_p)

P cross Q:
 [[-17]
 [-10]
 [  6]]
Q cross P:
 [[17]
 [10]
 [-6]]


In [203]:
# 11
result_11 = p_cross_q
print("Perpendicular to both P and Q:\n", result_11)
print()
print("Dot product should be 0:\n", "Dot P: ", (p_cross_q.T.dot(P)), "\n", "Dot Q: ",(p_cross_q.T.dot(Q)))

Perpendicular to both P and Q:
 [[-17]
 [-10]
 [  6]]

Dot product should be 0:
 Dot P:  [[0]] 
 Dot Q:  [[0]]


In [204]:
# 12
matrix_pqr = np.column_stack((P, Q, R))
determinant_pqr = np.linalg.det(matrix_pqr)
print(matrix_pqr)
print(f"Since determinate is {determinant_pqr} which != 0, P Q R are linearly independent")

[[ 2  0  1]
 [-1  3 -2]
 [ 4  5  2]]
Since determinate is 15.0 which != 0, P Q R are linearly independent


In [205]:
# 13
p_T_q = P.T.dot(Q)
print("P^T Q: ", p_T_q)

p_q_T = np.outer(P, Q)
print("P Q^T: \n", p_q_T)

P^T Q:  [[17]]
P Q^T: 
 [[ 0  6 10]
 [ 0 -3 -5]
 [ 0 12 20]]


### PART B

In [206]:
X = np.array([[2, 1, 0], [-1, 3, 4], [3, 2 ,-2]])
Y = np.array([[4, -1, 2], [3, 0, -3], [1, 2 ,1]])
Z = np.array([[2, 0, -1], [1, 4, 5], [3, 1, 2]])
s = np.array([-1, 4, 0])

In [207]:
# 1
result_1 = X + 2 * Y
print(result_1)

[[10 -1  4]
 [ 5  3 -2]
 [ 5  6  0]]


In [208]:
# 2
result_2a = np.dot(X, Y)
result_2b = np.dot(Y, X)
print("XY: ", result_2a)
print("YX: ", result_2b)

XY:  [[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
YX:  [[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]


In [209]:
# 3
result_3a = np.transpose(np.dot(X, Y))
print("(XY)^T:\n", result_3a)
print()
result_3b = np.dot(np.transpose(Y), np.transpose(X))
print("Y^T X^T:\n", result_3b)

(XY)^T:
 [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]

Y^T X^T:
 [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]


In [210]:
# 4
determinant_X = np.linalg.det(X)
determinant_Z = np.linalg.det(Z)
print("Determinant of X: ", determinant_X)
print("Determinant of Z: ", determinant_Z)
print("No linear dependency")

Determinant of X:  -17.999999999999996
Determinant of Z:  17.0
No linear dependency


In [211]:
# 5
# check if dot product between every pair is 0
def check_orthogonality(matrix):
    for i in range(matrix.shape[0]):
        for j in range(i + 1, matrix.shape[0]):
            if not np.isclose(np.dot(matrix[i], matrix[j]), 0):
                return False
    return True

is_X_orthogonal = check_orthogonality(X)
is_Y_orthogonal = check_orthogonality(Y)
is_Z_orthogonal = check_orthogonality(Z)
print(is_X_orthogonal, is_Y_orthogonal, is_Z_orthogonal)
print("None of the row vectors form an orthogonal set")

False False False
None of the row vectors form an orthogonal set


In [212]:
# 6
x_inv = np.linalg.inv(X)
y_inv = np.linalg.inv(Y)
print("X inverse:\n", x_inv)
print("Y inverse:\n", y_inv)


X inverse:
 [[ 0.77777778 -0.11111111 -0.22222222]
 [-0.55555556  0.22222222  0.44444444]
 [ 0.61111111  0.05555556 -0.38888889]]
Y inverse:
 [[ 0.14285714  0.11904762  0.07142857]
 [-0.14285714  0.04761905  0.42857143]
 [ 0.14285714 -0.21428571  0.07142857]]


In [213]:
# 7
z_inv = np.linalg.inv(Z)
print("Determinant of Z inverse: ", np.linalg.det(z_inv))
print("Z inverse:\n", z_inv)


Determinant of Z inverse:  0.0588235294117647
Z inverse:
 [[ 0.17647059 -0.05882353  0.23529412]
 [ 0.76470588  0.41176471 -0.64705882]
 [-0.64705882 -0.11764706  0.47058824]]


In [214]:
# 8 
product_Xs = np.dot(X, s).reshape(3, 1)
print("Product of X s:\n", product_Xs)


Product of X s:
 [[ 2]
 [13]
 [ 5]]


In [215]:
# 9
s_normalized = s / np.linalg.norm(s)
scalar_projections = np.array([np.dot(row, s_normalized) for row in X]).reshape(3, 1)
print("Scalar projection of rows of X onto s: \n", scalar_projections)

Scalar projection of rows of X onto s: 
 [[0.48507125]
 [3.15296313]
 [1.21267813]]


In [216]:
# 10
vector_projections = np.array([np.dot(row, s_normalized) * s_normalized for row in X])
print("Vector projection X onto s:\n", vector_projections)

Vector projection X onto s:
 [[-0.11764706  0.47058824  0.        ]
 [-0.76470588  3.05882353  0.        ]
 [-0.29411765  1.17647059  0.        ]]


In [217]:
# 11
linear_combination = s[0] * X[:, 0] + s[1] * X[:, 1] + s[2] * X[:, 2]
print("Linear combination of the columns of X using the elements of s:\n", linear_combination)

Linear combination of the columns of X using the elements of s:
 [ 2 13  5]


In [218]:
# 12
t_solution_for_Y_t_s = np.linalg.solve(Y, s)
print("Y t = s solution:\n", t_solution_for_Y_t_s)

Y t = s solution:
 [ 0.33333333  0.33333333 -1.        ]


In [219]:
# 13
t_solution_for_Z_t_s = np.linalg.solve(Z, s)
print("Z t = s solution:\n", t_solution_for_Z_t_s)


Z t = s solution:
 [-0.41176471  0.88235294  0.17647059]


### PART C

In [220]:
M = np.array([[3, 2], [-1, 4]])
N = np.array([[5, -3], [-3, 6]])
P = np.array([[2, 4], [4, 8]])

In [221]:
# 1
eigenvalues_M, eigenvectors_M = np.linalg.eig(M)
print("M eigenvalue: ", eigenvalues_M)
print("M eigenvector:\n", eigenvectors_M)

M eigenvalue:  [3.5+1.32287566j 3.5-1.32287566j]
M eigenvector:
 [[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415+0.54006172j 0.20412415-0.54006172j]]


In [222]:
# 2
dot_product_eigenvectors_M = np.dot(eigenvectors_M[:, 0], eigenvectors_M[:, 1])
print("Dot product between eigenvector of M: ", dot_product_eigenvectors_M)

Dot product between eigenvector of M:  (0.9999999999999998-9.010813772709382e-19j)


In [223]:
# 3
eigenvalues_N, eigenvectors_N = np.linalg.eig(N)
print("Eigenvector of N:\n", eigenvectors_N)
dot_product_eigenvectors_N = np.dot(eigenvectors_N[:, 0], eigenvectors_N[:, 1])
print("Dot product between eigenvector of N: ", dot_product_eigenvectors_N)

Eigenvector of N:
 [[-0.76301998  0.6463749 ]
 [-0.6463749  -0.76301998]]
Dot product between eigenvector of N:  9.102881516513367e-18


In [224]:
# 4
result_4 = "Since matrix N is symmetric, it has real eigenvalues and the eigenvectors are orthogonal"
print(result_4)

Since matrix N is symmetric, it has real eigenvalues and the eigenvectors are orthogonal


In [225]:
# 5
trivial_solution = np.array([0, 0])
print("Trivial solution: ", trivial_solution)

Trivial solution:  [0 0]


In [226]:
#6

import sympy as sp

matrix = sp.Matrix(P)
rref, _ =  matrix.rref()
print(rref)

Matrix([[1, 2], [0, 0]])


In [227]:
# 7

matrix = sp.Matrix(M)
rref, _ = matrix.rref()
print(rref)

Matrix([[1, 0], [0, 1]])


### PART D

In [228]:
# input values

x1, x2, x3 = 0.5, -0.8, 0.3
w1, w2, w3 = 0.4, -0.6, 0.9
b = 0.2

In [229]:
# 1

output = w1 * x1 + w2 * x2 + w3 * x3 + b
print("Output before activation: ", output)


Output before activation:  1.15


In [230]:
# 2
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

activation_value_sigmoid = sigmoid(output)
print("After sigmoid: ", activation_value_sigmoid)


After sigmoid:  0.759510916949111


In [231]:
# 3

def relu(x):
    return np.maximum(0, x)

activation_value_relu = relu(output)
print("After ReLU: ", activation_value_relu)


After ReLU:  1.15


In [232]:
Wh = np.array([[0.4, 0.3], [0.2, 0.7]])
bh = np.array([0.1, -0.1])
x = np.array([1, 2])

In [233]:
# 4
hidden_layer_output = relu(np.dot(Wh, x) + bh)
print("Output: ", hidden_layer_output)

Output:  [1.1 1.5]


In [234]:
# 5
Wo = np.array([0.5, -0.3])
bo = 0.1

output_layer_input = np.dot(Wo, hidden_layer_output) + bo
output_layer_output = sigmoid(output_layer_input)

print("Output after sigmoid activation", output_layer_output)


Output after sigmoid activation 0.549833997312478
